import uuid
from sqlalchemy import Column, Integer, String, Float, Text, ForeignKey, Enum
from sqlalchemy.ext.declarative import declarative_base
from src.enum.preference_enum import GenreEnum
from src.db import Base

class BookSummary(Base):
    __tablename__ = "book_summaries"

    id = Column(String(36), primary_key=True, index=True, default=lambda: str(uuid.uuid4()))
    book_id = Column(String(36), ForeignKey('book.book_id'), nullable=False, unique=True)
    book_rating = Column(Float, nullable=True)  # average rating (can be NULL if no ratings yet)
    book_review_summary = Column(Text, nullable=True)  # summarized from user reviews
    book_summary = Column(Text, nullable=True)  # generated by LLM
    genre = Column(Enum(GenreEnum), nullable=True)  # optional, can infer from book
